/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DataPagination: typeof import('./components/ui/DataPagination.vue')['default']
    EpisodeList: typeof import('./components/EpisodeList.vue')['default']
    HotVideos: typeof import('./components/HotVideos.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    PlayerHistory: typeof import('./components/PlayerHistory.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchCard: typeof import('./components/SearchCard.vue')['default']
    SearchContainer: typeof import('./components/SearchContainer.vue')['default']
    SearchInput: typeof import('./components/ui/SearchInput.vue')['default']
    SwitchResult: typeof import('./components/SwitchResult.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    VideoPlayer: typeof import('./components/VideoPlayer.vue')['default']
  }
}
