name: CI/CD

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: ghcr.io/${{ github.repository }}:latest

    steps:
      # 1️⃣ 拉取代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 3️⃣ 登录 GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # 4️⃣ 构建并推送 Docker 镜像
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}
          build-args: |
            GH_TOKEN=${{ secrets.GH_TOKEN }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # 5️⃣ 输出镜像信息
      - name: Image digest
        run: |
          echo "✅ Full-stack image: $DOCKER_IMAGE_NAME"